### ISSUE TITLE
Importing Spark

### ISSUE THREAD

**Issue by Mohamed3on** [jadianes/spark-movie-lens#24]
Hello,
As I was following the guide, I found the variable sc which was not defined, I figured it belonged to Spark. 
However, I don't know how to configure Spark to run the notebook.
I'm on windows, any help?

**Comment by fwoerister** [comment]
have you tried using pyspark?
https://medium.com/@GalarnykMichael/install-spark-on-windows-pyspark-4498a5d8d66c
