### ISSUE TITLE
GETing top recommendations shows the same movie 

### ISSUE THREAD

**Issue by marius92mc** [jadianes/spark-movie-lens#6]
Hello, 

I've managed to run the project **locally**, and the output from getting top recommendations shows the same movie. 
Does anyone else experience the same behavior? 
I mention that I've run it with the exact source files as in this repo. 

The mentioned **output** looks like this. 
"[["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30]]"

Thank you.

**Comment by jadianes** [comment]
It doesn't look right to me... What movies do you have in your ratings file?

**Comment by marius92mc** [comment]
The ratings.csv, as well as the entire dataset is not altered by me, is the same with the one from movie-lens archive link that is mentioned in the project tutorial.

I attach again two examples of retrieving the data. 

``` bash
$ curl http://0.0.0.0:5433/0/ratings/top/10
[["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30], ["The War (2007)", 8.836370207914264, 30]]
```

``` bash
$ curl http://0.0.0.0:5433/1/ratings/top/10
[["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887], ["\"Shawshank Redemption", 5.1801975606400665, 77887]]
```

**Comment by jadianes** [comment]
Ok. I'll have a look as soon as I find some time. In the meantime, if you try to find the error I'm sure you'll learn a lot about Spark. If you are able to fix it and the error is in the code provided, send us a pull request with the fix! :)

**Comment by marius92mc** [comment]
I've opened a PR regarding a **trivial** modification, but I mention that it <b>DOESN'T</b> fix this issue.

**Comment by marius92mc** [comment]
I've opened a PR that fixes this problem, by reverting the changes from #5. Those changes were causing the issue. 

Thank you.

**Comment by jadianes** [comment]
Thanks again. I made the #5 "fix" by suggestion without really looking at the results. My bad.
